### ISSUE TITLE
Different crash output on Exercise 1

### ISSUE THREAD

**Issue by smodnix** [antonio-morales/Fuzzing101#13]
I got different outputs:

filename: **id:000001,sig:11,src:001805,time:3011457,execs:1394662,op:havoc,rep:16**
```assembly
Error: Unterminated hex string
Error: Bad image parameters

Program received signal SIGSEGV, Segmentation fault.
EmbedStream::getChar (this=0x5555556ca2c0) at Stream.cc:787
787	  return str->getChar();
(gdb) bt
#0  EmbedStream::getChar (this=0x5555556ca2c0) at Stream.cc:787
#1  0x00005555555b5974 in Gfx::opBeginImage (this=0x5555556cc8e0, args=0x7fffffffd960, numArgs=0) at Gfx.cc:3880
#2  0x00005555555a3fec in Gfx::execOp (this=0x5555556cc8e0, cmd=0x7fffffffd950, args=0x7fffffffd960, numArgs=0) at Gfx.cc:690
#3  0x00005555555a39ee in Gfx::go (this=0x5555556cc8e0, topLevel=1) at Gfx.cc:581
#4  0x00005555555a37af in Gfx::display (this=0x5555556cc8e0, obj=0x7fffffffdcb0, topLevel=1) at Gfx.cc:553
#5  0x00005555555fc537 in Page::displaySlice (this=0x5555556c9c10, out=0x5555556cc570, hDPI=72, vDPI=72, rotate=0, useMediaBox=0, crop=0, sliceX=-1, sliceY=-1, 
    sliceW=-1, sliceH=-1, printing=0, catalog=0x5555556cb3e0, abortCheckCbk=0x0, abortCheckCbkData=0x0) at Page.cc:317
#6  0x00005555555fc128 in Page::display (this=0x5555556c9c10, out=0x5555556cc570, hDPI=72, vDPI=72, rotate=0, useMediaBox=0, crop=1, printing=0, 
    catalog=0x5555556cb3e0, abortCheckCbk=0x0, abortCheckCbkData=0x0) at Page.cc:264
#7  0x00005555555fed50 in PDFDoc::displayPage (this=0x5555556c8bb0, out=0x5555556cc570, page=1, hDPI=72, vDPI=72, rotate=0, useMediaBox=0, crop=1, printing=0, 
    abortCheckCbk=0x0, abortCheckCbkData=0x0) at PDFDoc.cc:317
#8  0x00005555555fedd5 in PDFDoc::displayPages (this=0x5555556c8bb0, out=0x5555556cc570, firstPage=1, lastPage=2, hDPI=72, vDPI=72, rotate=0, useMediaBox=0, 
    crop=1, printing=0, abortCheckCbk=0x0, abortCheckCbkData=0x0) at PDFDoc.cc:330
#9  0x0000555555622556 in main (argc=3, argv=0x7fffffffe018) at pdftotext.cc:237
```

filename: **id:000002,sig:11,src:001917,time:4388704,execs:2020321,op:havoc,rep:2**
```assembly
Error: Unterminated string

Program received signal SIGSEGV, Segmentation fault.
EmbedStream::getPos (this=0x5555556ca2c0) at Stream.h:364
364	  virtual int getPos() { return str->getPos(); }
(gdb) bt
#0  EmbedStream::getPos (this=0x5555556ca2c0) at Stream.h:364
#1  0x00005555556018e9 in Stream::makeFilter (this=0x5555556ca2c0, name=0x5555556ca3b0 "", str=0x5555556ca2c0, params=0x7fffffffd7d0) at Stream.cc:271
#2  0x0000555555600d70 in Stream::addFilters (this=0x5555556ca2c0, dict=0x7fffffffd840) at Stream.cc:110
#3  0x00005555555b5c9b in Gfx::buildImageStream (this=0x5555556cc8e0) at Gfx.cc:3925
#4  0x00005555555b5925 in Gfx::opBeginImage (this=0x5555556cc8e0, args=0x7fffffffd960, numArgs=0) at Gfx.cc:3873
#5  0x00005555555a3fec in Gfx::execOp (this=0x5555556cc8e0, cmd=0x7fffffffd950, args=0x7fffffffd960, numArgs=0) at Gfx.cc:690
#6  0x00005555555a39ee in Gfx::go (this=0x5555556cc8e0, topLevel=1) at Gfx.cc:581
#7  0x00005555555a37af in Gfx::display (this=0x5555556cc8e0, obj=0x7fffffffdcb0, topLevel=1) at Gfx.cc:553
#8  0x00005555555fc537 in Page::displaySlice (this=0x5555556c9c10, out=0x5555556cc570, hDPI=72, vDPI=72, rotate=0, useMediaBox=0, crop=0, sliceX=-1, sliceY=-1, 
    sliceW=-1, sliceH=-1, printing=0, catalog=0x5555556cb3e0, abortCheckCbk=0x0, abortCheckCbkData=0x0) at Page.cc:317
#9  0x00005555555fc128 in Page::display (this=0x5555556c9c10, out=0x5555556cc570, hDPI=72, vDPI=72, rotate=0, useMediaBox=0, crop=1, printing=0, 
    catalog=0x5555556cb3e0, abortCheckCbk=0x0, abortCheckCbkData=0x0) at Page.cc:264
#10 0x00005555555fed50 in PDFDoc::displayPage (this=0x5555556c8bb0, out=0x5555556cc570, page=1, hDPI=72, vDPI=72, rotate=0, useMediaBox=0, crop=1, printing=0, 
    abortCheckCbk=0x0, abortCheckCbkData=0x0) at PDFDoc.cc:317
#11 0x00005555555fedd5 in PDFDoc::displayPages (this=0x5555556c8bb0, out=0x5555556cc570, firstPage=1, lastPage=2, hDPI=72, vDPI=72, rotate=0, useMediaBox=0, 
    crop=1, printing=0, abortCheckCbk=0x0, abortCheckCbkData=0x0) at PDFDoc.cc:330
#12 0x0000555555622556 in main (argc=3, argv=0x7fffffffe018) at pdftotext.cc:237

```

**Comment by antonio-morales** [comment]
Hi @smodnix!

It looks like a different bug.

My advice is to report this vulnerability to the following address:  xpdf@xpdfreader.com, including all the information you have discovered and the input case that triggers the bug.

And let me know about what they reply to you

Regards

**Comment by smodnix** [comment]
Hi @antonio-morales,

I reported this to xpdfreader and they replied:
[https://forum.xpdfreader.com/viewtopic.php?f=1&t=42241&sid=6bdfae70c2cee23527d70aa524921515](https://forum.xpdfreader.com/viewtopic.php?f=1&t=42241&sid=6bdfae70c2cee23527d70aa524921515)

Regards, @smodnix

**Comment by n0bitaemon** [comment]
Hey, I know it's a long time since this post is published. But do you know the CVE ID for this bug?

**Comment by jin-jin0** [comment]
^ Lol just found this exact crash too
